VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "WorkStatus"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

'Resource
Public ResourceName As String

Public Application As String


'Activity
Public TaskName As String

'Activity
Public ActivityDesc As String

Public StartedOn As String

Public ExpectedCompletionOn As String

Public Status As String

Public Completion As String


Public Remarks As String


